#!/bin/bash 
         COUNTER=0
         while [  $COUNTER -lt 1000 ]; do
             echo The counter is $COUNTER
	          cat tweets.txt >> big_tweets.txt
             let COUNTER=COUNTER+1
         done
